// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xedgedetect_top.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XEdgedetect_top_CfgInitialize(XEdgedetect_top *InstancePtr, XEdgedetect_top_Config *ConfigPtr) {
    //Xil_AssertNonvoid(InstancePtr != NULL);
    //Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XEdgedetect_top_Start(XEdgedetect_top *InstancePtr) {
    u32 Data;

    //Xil_AssertVoid(InstancePtr != NULL);
    //Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEdgedetect_top_ReadReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XEdgedetect_top_WriteReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XEdgedetect_top_IsDone(XEdgedetect_top *InstancePtr) {
    u32 Data;

    //Xil_AssertNonvoid(InstancePtr != NULL);
    //Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEdgedetect_top_ReadReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XEdgedetect_top_IsIdle(XEdgedetect_top *InstancePtr) {
    u32 Data;

    //Xil_AssertNonvoid(InstancePtr != NULL);
    //Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEdgedetect_top_ReadReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XEdgedetect_top_IsReady(XEdgedetect_top *InstancePtr) {
    u32 Data;

    //Xil_AssertNonvoid(InstancePtr != NULL);
    //Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEdgedetect_top_ReadReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XEdgedetect_top_EnableAutoRestart(XEdgedetect_top *InstancePtr) {
    //Xil_AssertVoid(InstancePtr != NULL);
    //Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEdgedetect_top_WriteReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XEdgedetect_top_DisableAutoRestart(XEdgedetect_top *InstancePtr) {
    //Xil_AssertVoid(InstancePtr != NULL);
    //Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEdgedetect_top_WriteReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XEdgedetect_top_Set_rows(XEdgedetect_top *InstancePtr, u32 Data) {
    //Xil_AssertVoid(InstancePtr != NULL);
    //Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEdgedetect_top_WriteReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_ROWS_DATA, Data);
}

u32 XEdgedetect_top_Get_rows(XEdgedetect_top *InstancePtr) {
    u32 Data;

    //Xil_AssertNonvoid(InstancePtr != NULL);
    //Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEdgedetect_top_ReadReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_ROWS_DATA);
    return Data;
}

void XEdgedetect_top_Set_cols(XEdgedetect_top *InstancePtr, u32 Data) {
    //Xil_AssertVoid(InstancePtr != NULL);
    //Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEdgedetect_top_WriteReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_COLS_DATA, Data);
}

u32 XEdgedetect_top_Get_cols(XEdgedetect_top *InstancePtr) {
    u32 Data;

    //Xil_AssertNonvoid(InstancePtr != NULL);
    //Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEdgedetect_top_ReadReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_COLS_DATA);
    return Data;
}

void XEdgedetect_top_Set_threashold(XEdgedetect_top *InstancePtr, u32 Data) {
    //Xil_AssertVoid(InstancePtr != NULL);
    //Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEdgedetect_top_WriteReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_THREASHOLD_DATA, Data);
}

u32 XEdgedetect_top_Get_threashold(XEdgedetect_top *InstancePtr) {
    u32 Data;

    //Xil_AssertNonvoid(InstancePtr != NULL);
    //Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEdgedetect_top_ReadReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_THREASHOLD_DATA);
    return Data;
}

void XEdgedetect_top_InterruptGlobalEnable(XEdgedetect_top *InstancePtr) {
    //Xil_AssertVoid(InstancePtr != NULL);
    //Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEdgedetect_top_WriteReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_GIE, 1);
}

void XEdgedetect_top_InterruptGlobalDisable(XEdgedetect_top *InstancePtr) {
    //Xil_AssertVoid(InstancePtr != NULL);
    //Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEdgedetect_top_WriteReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_GIE, 0);
}

void XEdgedetect_top_InterruptEnable(XEdgedetect_top *InstancePtr, u32 Mask) {
    u32 Register;

    //Xil_AssertVoid(InstancePtr != NULL);
    //Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEdgedetect_top_ReadReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_IER);
    XEdgedetect_top_WriteReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XEdgedetect_top_InterruptDisable(XEdgedetect_top *InstancePtr, u32 Mask) {
    u32 Register;

    //Xil_AssertVoid(InstancePtr != NULL);
    //Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEdgedetect_top_ReadReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_IER);
    XEdgedetect_top_WriteReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XEdgedetect_top_InterruptClear(XEdgedetect_top *InstancePtr, u32 Mask) {
    //Xil_AssertVoid(InstancePtr != NULL);
    //Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEdgedetect_top_WriteReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XEdgedetect_top_InterruptGetEnabled(XEdgedetect_top *InstancePtr) {
    //Xil_AssertNonvoid(InstancePtr != NULL);
    //Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEdgedetect_top_ReadReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_IER);
}

u32 XEdgedetect_top_InterruptGetStatus(XEdgedetect_top *InstancePtr) {
    //Xil_AssertNonvoid(InstancePtr != NULL);
    //Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEdgedetect_top_ReadReg(InstancePtr->Control_bus_BaseAddress, XEDGEDETECT_TOP_CONTROL_BUS_ADDR_ISR);
}

