// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xedgedetect_top.h"

extern XEdgedetect_top_Config XEdgedetect_top_ConfigTable[];

XEdgedetect_top_Config *XEdgedetect_top_LookupConfig(u16 DeviceId) {
	XEdgedetect_top_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XEDGEDETECT_TOP_NUM_INSTANCES; Index++) {
		if (XEdgedetect_top_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XEdgedetect_top_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XEdgedetect_top_Initialize(XEdgedetect_top *InstancePtr, u16 DeviceId) {
	XEdgedetect_top_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XEdgedetect_top_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XEdgedetect_top_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

