webtalk_init -webtalk_dir C:/Users/zengh/Documents/xup/zedboard-axi-dma/Vivado/zedboard_axi_dma/zedboard_axi_dma.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Apr 27 17:58:59 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2015.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1412921" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211165549_0_0_263" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "bbdcf29c-ce4b-4db6-a536-a0bb28a98d94" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0daebcfd-2934-4a11-8667-8ab7522f90ba" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3293 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key pgmcnt -value "00:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "" -context "labtool\\usage"
webtalk_transmit -clientid 2685459312 -regid "211165549_0_0_263" -xml C:/Users/zengh/Documents/xup/zedboard-axi-dma/Vivado/zedboard_axi_dma/zedboard_axi_dma.hw/webtalk/usage_statistics_ext_labtool.xml -html C:/Users/zengh/Documents/xup/zedboard-axi-dma/Vivado/zedboard_axi_dma/zedboard_axi_dma.hw/webtalk/usage_statistics_ext_labtool.html -wdm C:/Users/zengh/Documents/xup/zedboard-axi-dma/Vivado/zedboard_axi_dma/zedboard_axi_dma.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
