// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="EdgeDetect_Top,hls_ip_2015_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=17.051000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=13,HLS_SYN_DSP=17,HLS_SYN_FF=1354,HLS_SYN_LUT=2576}" *)

module EdgeDetect_Top (
        input_V_data_V_dout,
        input_V_data_V_empty_n,
        input_V_data_V_read,
        input_V_keep_V_dout,
        input_V_keep_V_empty_n,
        input_V_keep_V_read,
        input_V_strb_V_dout,
        input_V_strb_V_empty_n,
        input_V_strb_V_read,
        input_V_user_V_dout,
        input_V_user_V_empty_n,
        input_V_user_V_read,
        input_V_last_V_dout,
        input_V_last_V_empty_n,
        input_V_last_V_read,
        input_V_id_V_dout,
        input_V_id_V_empty_n,
        input_V_id_V_read,
        input_V_dest_V_dout,
        input_V_dest_V_empty_n,
        input_V_dest_V_read,
        output_V_data_V_din,
        output_V_data_V_full_n,
        output_V_data_V_write,
        output_V_keep_V_din,
        output_V_keep_V_full_n,
        output_V_keep_V_write,
        output_V_strb_V_din,
        output_V_strb_V_full_n,
        output_V_strb_V_write,
        output_V_user_V_din,
        output_V_user_V_full_n,
        output_V_user_V_write,
        output_V_last_V_din,
        output_V_last_V_full_n,
        output_V_last_V_write,
        output_V_id_V_din,
        output_V_id_V_full_n,
        output_V_id_V_write,
        output_V_dest_V_din,
        output_V_dest_V_full_n,
        output_V_dest_V_write,
        rows,
        cols,
        threashold,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready
);

parameter    ap_const_logic_0 = 1'b0;
parameter    ap_const_lv24_0 = 24'b000000000000000000000000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_true = 1'b1;

input  [23:0] input_V_data_V_dout;
input   input_V_data_V_empty_n;
output   input_V_data_V_read;
input  [2:0] input_V_keep_V_dout;
input   input_V_keep_V_empty_n;
output   input_V_keep_V_read;
input  [2:0] input_V_strb_V_dout;
input   input_V_strb_V_empty_n;
output   input_V_strb_V_read;
input  [0:0] input_V_user_V_dout;
input   input_V_user_V_empty_n;
output   input_V_user_V_read;
input  [0:0] input_V_last_V_dout;
input   input_V_last_V_empty_n;
output   input_V_last_V_read;
input  [0:0] input_V_id_V_dout;
input   input_V_id_V_empty_n;
output   input_V_id_V_read;
input  [0:0] input_V_dest_V_dout;
input   input_V_dest_V_empty_n;
output   input_V_dest_V_read;
output  [23:0] output_V_data_V_din;
input   output_V_data_V_full_n;
output   output_V_data_V_write;
output  [2:0] output_V_keep_V_din;
input   output_V_keep_V_full_n;
output   output_V_keep_V_write;
output  [2:0] output_V_strb_V_din;
input   output_V_strb_V_full_n;
output   output_V_strb_V_write;
output  [0:0] output_V_user_V_din;
input   output_V_user_V_full_n;
output   output_V_user_V_write;
output  [0:0] output_V_last_V_din;
input   output_V_last_V_full_n;
output   output_V_last_V_write;
output  [0:0] output_V_id_V_din;
input   output_V_id_V_full_n;
output   output_V_id_V_write;
output  [0:0] output_V_dest_V_din;
input   output_V_dest_V_full_n;
output   output_V_dest_V_write;
input  [31:0] rows;
input  [31:0] cols;
input  [31:0] threashold;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;

reg ap_idle;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_ap_start;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_ap_done;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_ap_continue;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_ap_idle;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_ap_ready;
wire   [23:0] EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_data_V_dout;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_data_V_empty_n;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_data_V_read;
wire   [2:0] EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_keep_V_dout;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_keep_V_empty_n;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_keep_V_read;
wire   [2:0] EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_strb_V_dout;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_strb_V_empty_n;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_strb_V_read;
wire   [0:0] EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_user_V_dout;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_user_V_empty_n;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_user_V_read;
wire   [0:0] EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_last_V_dout;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_last_V_empty_n;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_last_V_read;
wire   [0:0] EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_id_V_dout;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_id_V_empty_n;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_id_V_read;
wire   [0:0] EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_dest_V_dout;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_dest_V_empty_n;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_dest_V_read;
wire   [7:0] EdgeDetect_Top_AXIvideo2Mat112_U0_rows;
wire   [7:0] EdgeDetect_Top_AXIvideo2Mat112_U0_cols;
wire   [7:0] EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_0_V_din;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_0_V_full_n;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_0_V_write;
wire   [7:0] EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_1_V_din;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_1_V_full_n;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_1_V_write;
wire   [7:0] EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_2_V_din;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_2_V_full_n;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_2_V_write;
wire   [31:0] EdgeDetect_Top_AXIvideo2Mat112_U0_threashold;
wire   [31:0] EdgeDetect_Top_AXIvideo2Mat112_U0_threashold_out_din;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_threashold_out_full_n;
wire    EdgeDetect_Top_AXIvideo2Mat112_U0_threashold_out_write;
wire    EdgeDetect_Top_GaussianBlur_U0_ap_start;
wire    EdgeDetect_Top_GaussianBlur_U0_ap_done;
wire    EdgeDetect_Top_GaussianBlur_U0_ap_continue;
wire    EdgeDetect_Top_GaussianBlur_U0_ap_idle;
wire    EdgeDetect_Top_GaussianBlur_U0_ap_ready;
wire   [7:0] EdgeDetect_Top_GaussianBlur_U0_rows;
wire   [7:0] EdgeDetect_Top_GaussianBlur_U0_cols;
wire   [7:0] EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_0_V_dout;
wire    EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_0_V_empty_n;
wire    EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_0_V_read;
wire   [7:0] EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_1_V_dout;
wire    EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_1_V_empty_n;
wire    EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_1_V_read;
wire   [7:0] EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_2_V_dout;
wire    EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_2_V_empty_n;
wire    EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_2_V_read;
wire   [7:0] EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_0_V_din;
wire    EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_0_V_full_n;
wire    EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_0_V_write;
wire   [7:0] EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_1_V_din;
wire    EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_1_V_full_n;
wire    EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_1_V_write;
wire   [7:0] EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_2_V_din;
wire    EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_2_V_full_n;
wire    EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_2_V_write;
wire    EdgeDetect_Top_CvtColor_U0_ap_start;
wire    EdgeDetect_Top_CvtColor_U0_ap_done;
wire    EdgeDetect_Top_CvtColor_U0_ap_continue;
wire    EdgeDetect_Top_CvtColor_U0_ap_idle;
wire    EdgeDetect_Top_CvtColor_U0_ap_ready;
wire   [7:0] EdgeDetect_Top_CvtColor_U0_rows;
wire   [7:0] EdgeDetect_Top_CvtColor_U0_cols;
wire   [7:0] EdgeDetect_Top_CvtColor_U0_p_src_data_stream_0_V_dout;
wire    EdgeDetect_Top_CvtColor_U0_p_src_data_stream_0_V_empty_n;
wire    EdgeDetect_Top_CvtColor_U0_p_src_data_stream_0_V_read;
wire   [7:0] EdgeDetect_Top_CvtColor_U0_p_src_data_stream_1_V_dout;
wire    EdgeDetect_Top_CvtColor_U0_p_src_data_stream_1_V_empty_n;
wire    EdgeDetect_Top_CvtColor_U0_p_src_data_stream_1_V_read;
wire   [7:0] EdgeDetect_Top_CvtColor_U0_p_src_data_stream_2_V_dout;
wire    EdgeDetect_Top_CvtColor_U0_p_src_data_stream_2_V_empty_n;
wire    EdgeDetect_Top_CvtColor_U0_p_src_data_stream_2_V_read;
wire   [7:0] EdgeDetect_Top_CvtColor_U0_p_dst_data_stream_V_din;
wire    EdgeDetect_Top_CvtColor_U0_p_dst_data_stream_V_full_n;
wire    EdgeDetect_Top_CvtColor_U0_p_dst_data_stream_V_write;
wire    EdgeDetect_Top_ImgProcess_0_0_128_128_U0_ap_start;
wire    EdgeDetect_Top_ImgProcess_0_0_128_128_U0_ap_done;
wire    EdgeDetect_Top_ImgProcess_0_0_128_128_U0_ap_continue;
wire    EdgeDetect_Top_ImgProcess_0_0_128_128_U0_ap_idle;
wire    EdgeDetect_Top_ImgProcess_0_0_128_128_U0_ap_ready;
wire   [7:0] EdgeDetect_Top_ImgProcess_0_0_128_128_U0_p_src_data_stream_V_dout;
wire    EdgeDetect_Top_ImgProcess_0_0_128_128_U0_p_src_data_stream_V_empty_n;
wire    EdgeDetect_Top_ImgProcess_0_0_128_128_U0_p_src_data_stream_V_read;
wire   [7:0] EdgeDetect_Top_ImgProcess_0_0_128_128_U0_p_dst_data_stream_V_din;
wire    EdgeDetect_Top_ImgProcess_0_0_128_128_U0_p_dst_data_stream_V_full_n;
wire    EdgeDetect_Top_ImgProcess_0_0_128_128_U0_p_dst_data_stream_V_write;
wire   [31:0] EdgeDetect_Top_ImgProcess_0_0_128_128_U0_threashold_dout;
wire    EdgeDetect_Top_ImgProcess_0_0_128_128_U0_threashold_empty_n;
wire    EdgeDetect_Top_ImgProcess_0_0_128_128_U0_threashold_read;
wire   [7:0] EdgeDetect_Top_ImgProcess_0_0_128_128_U0_width;
wire   [7:0] EdgeDetect_Top_ImgProcess_0_0_128_128_U0_height;
wire    EdgeDetect_Top_CvtColor_1_U0_ap_start;
wire    EdgeDetect_Top_CvtColor_1_U0_ap_done;
wire    EdgeDetect_Top_CvtColor_1_U0_ap_continue;
wire    EdgeDetect_Top_CvtColor_1_U0_ap_idle;
wire    EdgeDetect_Top_CvtColor_1_U0_ap_ready;
wire   [7:0] EdgeDetect_Top_CvtColor_1_U0_rows;
wire   [7:0] EdgeDetect_Top_CvtColor_1_U0_cols;
wire   [7:0] EdgeDetect_Top_CvtColor_1_U0_p_src_data_stream_V_dout;
wire    EdgeDetect_Top_CvtColor_1_U0_p_src_data_stream_V_empty_n;
wire    EdgeDetect_Top_CvtColor_1_U0_p_src_data_stream_V_read;
wire   [7:0] EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_0_V_din;
wire    EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_0_V_full_n;
wire    EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_0_V_write;
wire   [7:0] EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_1_V_din;
wire    EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_1_V_full_n;
wire    EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_1_V_write;
wire   [7:0] EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_2_V_din;
wire    EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_2_V_full_n;
wire    EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_2_V_write;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_ap_start;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_ap_done;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_ap_continue;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_ap_idle;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_ap_ready;
wire   [7:0] EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_rows;
wire   [7:0] EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_cols;
wire   [7:0] EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_0_V_dout;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_0_V_empty_n;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_0_V_read;
wire   [7:0] EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_1_V_dout;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_1_V_empty_n;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_1_V_read;
wire   [7:0] EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_2_V_dout;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_2_V_empty_n;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_2_V_read;
wire   [23:0] EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_data_V_din;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_data_V_full_n;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_data_V_write;
wire   [2:0] EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_keep_V_din;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_keep_V_full_n;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_keep_V_write;
wire   [2:0] EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_strb_V_din;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_strb_V_full_n;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_strb_V_write;
wire   [0:0] EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_user_V_din;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_user_V_full_n;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_user_V_write;
wire   [0:0] EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_last_V_din;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_last_V_full_n;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_last_V_write;
wire   [0:0] EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_id_V_din;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_id_V_full_n;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_id_V_write;
wire   [0:0] EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_dest_V_din;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_dest_V_full_n;
wire    EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_dest_V_write;
wire    ap_sig_hs_continue;
wire    src_mat_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] src_mat_data_stream_0_V_din;
wire    src_mat_data_stream_0_V_full_n;
wire    src_mat_data_stream_0_V_write;
wire   [7:0] src_mat_data_stream_0_V_dout;
wire    src_mat_data_stream_0_V_empty_n;
wire    src_mat_data_stream_0_V_read;
wire    src_mat_data_stream_1_V_U_ap_dummy_ce;
wire   [7:0] src_mat_data_stream_1_V_din;
wire    src_mat_data_stream_1_V_full_n;
wire    src_mat_data_stream_1_V_write;
wire   [7:0] src_mat_data_stream_1_V_dout;
wire    src_mat_data_stream_1_V_empty_n;
wire    src_mat_data_stream_1_V_read;
wire    src_mat_data_stream_2_V_U_ap_dummy_ce;
wire   [7:0] src_mat_data_stream_2_V_din;
wire    src_mat_data_stream_2_V_full_n;
wire    src_mat_data_stream_2_V_write;
wire   [7:0] src_mat_data_stream_2_V_dout;
wire    src_mat_data_stream_2_V_empty_n;
wire    src_mat_data_stream_2_V_read;
wire    threashold_channel_U_ap_dummy_ce;
wire   [31:0] threashold_channel_din;
wire    threashold_channel_full_n;
wire    threashold_channel_write;
wire   [31:0] threashold_channel_dout;
wire    threashold_channel_empty_n;
wire    threashold_channel_read;
wire    b_src_mat_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] b_src_mat_data_stream_0_V_din;
wire    b_src_mat_data_stream_0_V_full_n;
wire    b_src_mat_data_stream_0_V_write;
wire   [7:0] b_src_mat_data_stream_0_V_dout;
wire    b_src_mat_data_stream_0_V_empty_n;
wire    b_src_mat_data_stream_0_V_read;
wire    b_src_mat_data_stream_1_V_U_ap_dummy_ce;
wire   [7:0] b_src_mat_data_stream_1_V_din;
wire    b_src_mat_data_stream_1_V_full_n;
wire    b_src_mat_data_stream_1_V_write;
wire   [7:0] b_src_mat_data_stream_1_V_dout;
wire    b_src_mat_data_stream_1_V_empty_n;
wire    b_src_mat_data_stream_1_V_read;
wire    b_src_mat_data_stream_2_V_U_ap_dummy_ce;
wire   [7:0] b_src_mat_data_stream_2_V_din;
wire    b_src_mat_data_stream_2_V_full_n;
wire    b_src_mat_data_stream_2_V_write;
wire   [7:0] b_src_mat_data_stream_2_V_dout;
wire    b_src_mat_data_stream_2_V_empty_n;
wire    b_src_mat_data_stream_2_V_read;
wire    g_src_mat_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] g_src_mat_data_stream_0_V_din;
wire    g_src_mat_data_stream_0_V_full_n;
wire    g_src_mat_data_stream_0_V_write;
wire   [7:0] g_src_mat_data_stream_0_V_dout;
wire    g_src_mat_data_stream_0_V_empty_n;
wire    g_src_mat_data_stream_0_V_read;
wire    g_dst_mat_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] g_dst_mat_data_stream_0_V_din;
wire    g_dst_mat_data_stream_0_V_full_n;
wire    g_dst_mat_data_stream_0_V_write;
wire   [7:0] g_dst_mat_data_stream_0_V_dout;
wire    g_dst_mat_data_stream_0_V_empty_n;
wire    g_dst_mat_data_stream_0_V_read;
wire    dst_mat_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] dst_mat_data_stream_0_V_din;
wire    dst_mat_data_stream_0_V_full_n;
wire    dst_mat_data_stream_0_V_write;
wire   [7:0] dst_mat_data_stream_0_V_dout;
wire    dst_mat_data_stream_0_V_empty_n;
wire    dst_mat_data_stream_0_V_read;
wire    dst_mat_data_stream_1_V_U_ap_dummy_ce;
wire   [7:0] dst_mat_data_stream_1_V_din;
wire    dst_mat_data_stream_1_V_full_n;
wire    dst_mat_data_stream_1_V_write;
wire   [7:0] dst_mat_data_stream_1_V_dout;
wire    dst_mat_data_stream_1_V_empty_n;
wire    dst_mat_data_stream_1_V_read;
wire    dst_mat_data_stream_2_V_U_ap_dummy_ce;
wire   [7:0] dst_mat_data_stream_2_V_din;
wire    dst_mat_data_stream_2_V_full_n;
wire    dst_mat_data_stream_2_V_write;
wire   [7:0] dst_mat_data_stream_2_V_dout;
wire    dst_mat_data_stream_2_V_empty_n;
wire    dst_mat_data_stream_2_V_read;
reg    ap_reg_procdone_EdgeDetect_Top_AXIvideo2Mat112_U0 = 1'b0;
reg    ap_sig_hs_done;
reg    ap_reg_procdone_EdgeDetect_Top_GaussianBlur_U0 = 1'b0;
reg    ap_reg_procdone_EdgeDetect_Top_CvtColor_U0 = 1'b0;
reg    ap_reg_procdone_EdgeDetect_Top_ImgProcess_0_0_128_128_U0 = 1'b0;
reg    ap_reg_procdone_EdgeDetect_Top_CvtColor_1_U0 = 1'b0;
reg    ap_reg_procdone_EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0 = 1'b0;
reg    ap_CS;
wire    ap_sig_top_allready;


EdgeDetect_Top_AXIvideo2Mat112 EdgeDetect_Top_AXIvideo2Mat112_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( EdgeDetect_Top_AXIvideo2Mat112_U0_ap_start ),
    .ap_done( EdgeDetect_Top_AXIvideo2Mat112_U0_ap_done ),
    .ap_continue( EdgeDetect_Top_AXIvideo2Mat112_U0_ap_continue ),
    .ap_idle( EdgeDetect_Top_AXIvideo2Mat112_U0_ap_idle ),
    .ap_ready( EdgeDetect_Top_AXIvideo2Mat112_U0_ap_ready ),
    .input_V_data_V_dout( EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_data_V_dout ),
    .input_V_data_V_empty_n( EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_data_V_empty_n ),
    .input_V_data_V_read( EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_data_V_read ),
    .input_V_keep_V_dout( EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_keep_V_dout ),
    .input_V_keep_V_empty_n( EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_keep_V_empty_n ),
    .input_V_keep_V_read( EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_keep_V_read ),
    .input_V_strb_V_dout( EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_strb_V_dout ),
    .input_V_strb_V_empty_n( EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_strb_V_empty_n ),
    .input_V_strb_V_read( EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_strb_V_read ),
    .input_V_user_V_dout( EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_user_V_dout ),
    .input_V_user_V_empty_n( EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_user_V_empty_n ),
    .input_V_user_V_read( EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_user_V_read ),
    .input_V_last_V_dout( EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_last_V_dout ),
    .input_V_last_V_empty_n( EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_last_V_empty_n ),
    .input_V_last_V_read( EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_last_V_read ),
    .input_V_id_V_dout( EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_id_V_dout ),
    .input_V_id_V_empty_n( EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_id_V_empty_n ),
    .input_V_id_V_read( EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_id_V_read ),
    .input_V_dest_V_dout( EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_dest_V_dout ),
    .input_V_dest_V_empty_n( EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_dest_V_empty_n ),
    .input_V_dest_V_read( EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_dest_V_read ),
    .rows( EdgeDetect_Top_AXIvideo2Mat112_U0_rows ),
    .cols( EdgeDetect_Top_AXIvideo2Mat112_U0_cols ),
    .src_mat_data_stream_0_V_din( EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_0_V_din ),
    .src_mat_data_stream_0_V_full_n( EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_0_V_full_n ),
    .src_mat_data_stream_0_V_write( EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_0_V_write ),
    .src_mat_data_stream_1_V_din( EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_1_V_din ),
    .src_mat_data_stream_1_V_full_n( EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_1_V_full_n ),
    .src_mat_data_stream_1_V_write( EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_1_V_write ),
    .src_mat_data_stream_2_V_din( EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_2_V_din ),
    .src_mat_data_stream_2_V_full_n( EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_2_V_full_n ),
    .src_mat_data_stream_2_V_write( EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_2_V_write ),
    .threashold( EdgeDetect_Top_AXIvideo2Mat112_U0_threashold ),
    .threashold_out_din( EdgeDetect_Top_AXIvideo2Mat112_U0_threashold_out_din ),
    .threashold_out_full_n( EdgeDetect_Top_AXIvideo2Mat112_U0_threashold_out_full_n ),
    .threashold_out_write( EdgeDetect_Top_AXIvideo2Mat112_U0_threashold_out_write )
);

EdgeDetect_Top_GaussianBlur EdgeDetect_Top_GaussianBlur_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( EdgeDetect_Top_GaussianBlur_U0_ap_start ),
    .ap_done( EdgeDetect_Top_GaussianBlur_U0_ap_done ),
    .ap_continue( EdgeDetect_Top_GaussianBlur_U0_ap_continue ),
    .ap_idle( EdgeDetect_Top_GaussianBlur_U0_ap_idle ),
    .ap_ready( EdgeDetect_Top_GaussianBlur_U0_ap_ready ),
    .rows( EdgeDetect_Top_GaussianBlur_U0_rows ),
    .cols( EdgeDetect_Top_GaussianBlur_U0_cols ),
    .p_src_data_stream_0_V_dout( EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_0_V_dout ),
    .p_src_data_stream_0_V_empty_n( EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_0_V_empty_n ),
    .p_src_data_stream_0_V_read( EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_0_V_read ),
    .p_src_data_stream_1_V_dout( EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_1_V_dout ),
    .p_src_data_stream_1_V_empty_n( EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_1_V_empty_n ),
    .p_src_data_stream_1_V_read( EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_1_V_read ),
    .p_src_data_stream_2_V_dout( EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_2_V_dout ),
    .p_src_data_stream_2_V_empty_n( EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_2_V_empty_n ),
    .p_src_data_stream_2_V_read( EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_2_V_read ),
    .p_dst_data_stream_0_V_din( EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_0_V_din ),
    .p_dst_data_stream_0_V_full_n( EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_0_V_full_n ),
    .p_dst_data_stream_0_V_write( EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_0_V_write ),
    .p_dst_data_stream_1_V_din( EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_1_V_din ),
    .p_dst_data_stream_1_V_full_n( EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_1_V_full_n ),
    .p_dst_data_stream_1_V_write( EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_1_V_write ),
    .p_dst_data_stream_2_V_din( EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_2_V_din ),
    .p_dst_data_stream_2_V_full_n( EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_2_V_full_n ),
    .p_dst_data_stream_2_V_write( EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_2_V_write )
);

EdgeDetect_Top_CvtColor EdgeDetect_Top_CvtColor_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( EdgeDetect_Top_CvtColor_U0_ap_start ),
    .ap_done( EdgeDetect_Top_CvtColor_U0_ap_done ),
    .ap_continue( EdgeDetect_Top_CvtColor_U0_ap_continue ),
    .ap_idle( EdgeDetect_Top_CvtColor_U0_ap_idle ),
    .ap_ready( EdgeDetect_Top_CvtColor_U0_ap_ready ),
    .rows( EdgeDetect_Top_CvtColor_U0_rows ),
    .cols( EdgeDetect_Top_CvtColor_U0_cols ),
    .p_src_data_stream_0_V_dout( EdgeDetect_Top_CvtColor_U0_p_src_data_stream_0_V_dout ),
    .p_src_data_stream_0_V_empty_n( EdgeDetect_Top_CvtColor_U0_p_src_data_stream_0_V_empty_n ),
    .p_src_data_stream_0_V_read( EdgeDetect_Top_CvtColor_U0_p_src_data_stream_0_V_read ),
    .p_src_data_stream_1_V_dout( EdgeDetect_Top_CvtColor_U0_p_src_data_stream_1_V_dout ),
    .p_src_data_stream_1_V_empty_n( EdgeDetect_Top_CvtColor_U0_p_src_data_stream_1_V_empty_n ),
    .p_src_data_stream_1_V_read( EdgeDetect_Top_CvtColor_U0_p_src_data_stream_1_V_read ),
    .p_src_data_stream_2_V_dout( EdgeDetect_Top_CvtColor_U0_p_src_data_stream_2_V_dout ),
    .p_src_data_stream_2_V_empty_n( EdgeDetect_Top_CvtColor_U0_p_src_data_stream_2_V_empty_n ),
    .p_src_data_stream_2_V_read( EdgeDetect_Top_CvtColor_U0_p_src_data_stream_2_V_read ),
    .p_dst_data_stream_V_din( EdgeDetect_Top_CvtColor_U0_p_dst_data_stream_V_din ),
    .p_dst_data_stream_V_full_n( EdgeDetect_Top_CvtColor_U0_p_dst_data_stream_V_full_n ),
    .p_dst_data_stream_V_write( EdgeDetect_Top_CvtColor_U0_p_dst_data_stream_V_write )
);

EdgeDetect_Top_ImgProcess_0_0_128_128_s EdgeDetect_Top_ImgProcess_0_0_128_128_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( EdgeDetect_Top_ImgProcess_0_0_128_128_U0_ap_start ),
    .ap_done( EdgeDetect_Top_ImgProcess_0_0_128_128_U0_ap_done ),
    .ap_continue( EdgeDetect_Top_ImgProcess_0_0_128_128_U0_ap_continue ),
    .ap_idle( EdgeDetect_Top_ImgProcess_0_0_128_128_U0_ap_idle ),
    .ap_ready( EdgeDetect_Top_ImgProcess_0_0_128_128_U0_ap_ready ),
    .p_src_data_stream_V_dout( EdgeDetect_Top_ImgProcess_0_0_128_128_U0_p_src_data_stream_V_dout ),
    .p_src_data_stream_V_empty_n( EdgeDetect_Top_ImgProcess_0_0_128_128_U0_p_src_data_stream_V_empty_n ),
    .p_src_data_stream_V_read( EdgeDetect_Top_ImgProcess_0_0_128_128_U0_p_src_data_stream_V_read ),
    .p_dst_data_stream_V_din( EdgeDetect_Top_ImgProcess_0_0_128_128_U0_p_dst_data_stream_V_din ),
    .p_dst_data_stream_V_full_n( EdgeDetect_Top_ImgProcess_0_0_128_128_U0_p_dst_data_stream_V_full_n ),
    .p_dst_data_stream_V_write( EdgeDetect_Top_ImgProcess_0_0_128_128_U0_p_dst_data_stream_V_write ),
    .threashold_dout( EdgeDetect_Top_ImgProcess_0_0_128_128_U0_threashold_dout ),
    .threashold_empty_n( EdgeDetect_Top_ImgProcess_0_0_128_128_U0_threashold_empty_n ),
    .threashold_read( EdgeDetect_Top_ImgProcess_0_0_128_128_U0_threashold_read ),
    .width( EdgeDetect_Top_ImgProcess_0_0_128_128_U0_width ),
    .height( EdgeDetect_Top_ImgProcess_0_0_128_128_U0_height )
);

EdgeDetect_Top_CvtColor_1 EdgeDetect_Top_CvtColor_1_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( EdgeDetect_Top_CvtColor_1_U0_ap_start ),
    .ap_done( EdgeDetect_Top_CvtColor_1_U0_ap_done ),
    .ap_continue( EdgeDetect_Top_CvtColor_1_U0_ap_continue ),
    .ap_idle( EdgeDetect_Top_CvtColor_1_U0_ap_idle ),
    .ap_ready( EdgeDetect_Top_CvtColor_1_U0_ap_ready ),
    .rows( EdgeDetect_Top_CvtColor_1_U0_rows ),
    .cols( EdgeDetect_Top_CvtColor_1_U0_cols ),
    .p_src_data_stream_V_dout( EdgeDetect_Top_CvtColor_1_U0_p_src_data_stream_V_dout ),
    .p_src_data_stream_V_empty_n( EdgeDetect_Top_CvtColor_1_U0_p_src_data_stream_V_empty_n ),
    .p_src_data_stream_V_read( EdgeDetect_Top_CvtColor_1_U0_p_src_data_stream_V_read ),
    .p_dst_data_stream_0_V_din( EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_0_V_din ),
    .p_dst_data_stream_0_V_full_n( EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_0_V_full_n ),
    .p_dst_data_stream_0_V_write( EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_0_V_write ),
    .p_dst_data_stream_1_V_din( EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_1_V_din ),
    .p_dst_data_stream_1_V_full_n( EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_1_V_full_n ),
    .p_dst_data_stream_1_V_write( EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_1_V_write ),
    .p_dst_data_stream_2_V_din( EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_2_V_din ),
    .p_dst_data_stream_2_V_full_n( EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_2_V_full_n ),
    .p_dst_data_stream_2_V_write( EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_2_V_write )
);

EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_s EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_ap_start ),
    .ap_done( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_ap_done ),
    .ap_continue( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_ap_continue ),
    .ap_idle( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_ap_idle ),
    .ap_ready( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_ap_ready ),
    .rows( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_rows ),
    .cols( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_cols ),
    .img_data_stream_0_V_dout( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_0_V_dout ),
    .img_data_stream_0_V_empty_n( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_0_V_empty_n ),
    .img_data_stream_0_V_read( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_0_V_read ),
    .img_data_stream_1_V_dout( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_1_V_dout ),
    .img_data_stream_1_V_empty_n( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_1_V_empty_n ),
    .img_data_stream_1_V_read( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_1_V_read ),
    .img_data_stream_2_V_dout( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_2_V_dout ),
    .img_data_stream_2_V_empty_n( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_2_V_empty_n ),
    .img_data_stream_2_V_read( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_2_V_read ),
    .AXI_video_strm_V_data_V_din( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_data_V_din ),
    .AXI_video_strm_V_data_V_full_n( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_data_V_full_n ),
    .AXI_video_strm_V_data_V_write( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_data_V_write ),
    .AXI_video_strm_V_keep_V_din( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_keep_V_din ),
    .AXI_video_strm_V_keep_V_full_n( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_keep_V_full_n ),
    .AXI_video_strm_V_keep_V_write( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_keep_V_write ),
    .AXI_video_strm_V_strb_V_din( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_strb_V_din ),
    .AXI_video_strm_V_strb_V_full_n( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_strb_V_full_n ),
    .AXI_video_strm_V_strb_V_write( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_strb_V_write ),
    .AXI_video_strm_V_user_V_din( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_user_V_din ),
    .AXI_video_strm_V_user_V_full_n( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_user_V_full_n ),
    .AXI_video_strm_V_user_V_write( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_user_V_write ),
    .AXI_video_strm_V_last_V_din( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_last_V_din ),
    .AXI_video_strm_V_last_V_full_n( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_last_V_full_n ),
    .AXI_video_strm_V_last_V_write( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_last_V_write ),
    .AXI_video_strm_V_id_V_din( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_id_V_din ),
    .AXI_video_strm_V_id_V_full_n( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_id_V_full_n ),
    .AXI_video_strm_V_id_V_write( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_id_V_write ),
    .AXI_video_strm_V_dest_V_din( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_dest_V_din ),
    .AXI_video_strm_V_dest_V_full_n( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_dest_V_full_n ),
    .AXI_video_strm_V_dest_V_write( EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_dest_V_write )
);

FIFO_EdgeDetect_Top_src_mat_data_stream_0_V src_mat_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .if_read_ce( src_mat_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( src_mat_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( src_mat_data_stream_0_V_din ),
    .if_full_n( src_mat_data_stream_0_V_full_n ),
    .if_write( src_mat_data_stream_0_V_write ),
    .if_dout( src_mat_data_stream_0_V_dout ),
    .if_empty_n( src_mat_data_stream_0_V_empty_n ),
    .if_read( src_mat_data_stream_0_V_read )
);

FIFO_EdgeDetect_Top_src_mat_data_stream_1_V src_mat_data_stream_1_V_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .if_read_ce( src_mat_data_stream_1_V_U_ap_dummy_ce ),
    .if_write_ce( src_mat_data_stream_1_V_U_ap_dummy_ce ),
    .if_din( src_mat_data_stream_1_V_din ),
    .if_full_n( src_mat_data_stream_1_V_full_n ),
    .if_write( src_mat_data_stream_1_V_write ),
    .if_dout( src_mat_data_stream_1_V_dout ),
    .if_empty_n( src_mat_data_stream_1_V_empty_n ),
    .if_read( src_mat_data_stream_1_V_read )
);

FIFO_EdgeDetect_Top_src_mat_data_stream_2_V src_mat_data_stream_2_V_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .if_read_ce( src_mat_data_stream_2_V_U_ap_dummy_ce ),
    .if_write_ce( src_mat_data_stream_2_V_U_ap_dummy_ce ),
    .if_din( src_mat_data_stream_2_V_din ),
    .if_full_n( src_mat_data_stream_2_V_full_n ),
    .if_write( src_mat_data_stream_2_V_write ),
    .if_dout( src_mat_data_stream_2_V_dout ),
    .if_empty_n( src_mat_data_stream_2_V_empty_n ),
    .if_read( src_mat_data_stream_2_V_read )
);

FIFO_EdgeDetect_Top_threashold_channel threashold_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .if_read_ce( threashold_channel_U_ap_dummy_ce ),
    .if_write_ce( threashold_channel_U_ap_dummy_ce ),
    .if_din( threashold_channel_din ),
    .if_full_n( threashold_channel_full_n ),
    .if_write( threashold_channel_write ),
    .if_dout( threashold_channel_dout ),
    .if_empty_n( threashold_channel_empty_n ),
    .if_read( threashold_channel_read )
);

FIFO_EdgeDetect_Top_b_src_mat_data_stream_0_V b_src_mat_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .if_read_ce( b_src_mat_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( b_src_mat_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( b_src_mat_data_stream_0_V_din ),
    .if_full_n( b_src_mat_data_stream_0_V_full_n ),
    .if_write( b_src_mat_data_stream_0_V_write ),
    .if_dout( b_src_mat_data_stream_0_V_dout ),
    .if_empty_n( b_src_mat_data_stream_0_V_empty_n ),
    .if_read( b_src_mat_data_stream_0_V_read )
);

FIFO_EdgeDetect_Top_b_src_mat_data_stream_1_V b_src_mat_data_stream_1_V_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .if_read_ce( b_src_mat_data_stream_1_V_U_ap_dummy_ce ),
    .if_write_ce( b_src_mat_data_stream_1_V_U_ap_dummy_ce ),
    .if_din( b_src_mat_data_stream_1_V_din ),
    .if_full_n( b_src_mat_data_stream_1_V_full_n ),
    .if_write( b_src_mat_data_stream_1_V_write ),
    .if_dout( b_src_mat_data_stream_1_V_dout ),
    .if_empty_n( b_src_mat_data_stream_1_V_empty_n ),
    .if_read( b_src_mat_data_stream_1_V_read )
);

FIFO_EdgeDetect_Top_b_src_mat_data_stream_2_V b_src_mat_data_stream_2_V_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .if_read_ce( b_src_mat_data_stream_2_V_U_ap_dummy_ce ),
    .if_write_ce( b_src_mat_data_stream_2_V_U_ap_dummy_ce ),
    .if_din( b_src_mat_data_stream_2_V_din ),
    .if_full_n( b_src_mat_data_stream_2_V_full_n ),
    .if_write( b_src_mat_data_stream_2_V_write ),
    .if_dout( b_src_mat_data_stream_2_V_dout ),
    .if_empty_n( b_src_mat_data_stream_2_V_empty_n ),
    .if_read( b_src_mat_data_stream_2_V_read )
);

FIFO_EdgeDetect_Top_g_src_mat_data_stream_0_V g_src_mat_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .if_read_ce( g_src_mat_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( g_src_mat_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( g_src_mat_data_stream_0_V_din ),
    .if_full_n( g_src_mat_data_stream_0_V_full_n ),
    .if_write( g_src_mat_data_stream_0_V_write ),
    .if_dout( g_src_mat_data_stream_0_V_dout ),
    .if_empty_n( g_src_mat_data_stream_0_V_empty_n ),
    .if_read( g_src_mat_data_stream_0_V_read )
);

FIFO_EdgeDetect_Top_g_dst_mat_data_stream_0_V g_dst_mat_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .if_read_ce( g_dst_mat_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( g_dst_mat_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( g_dst_mat_data_stream_0_V_din ),
    .if_full_n( g_dst_mat_data_stream_0_V_full_n ),
    .if_write( g_dst_mat_data_stream_0_V_write ),
    .if_dout( g_dst_mat_data_stream_0_V_dout ),
    .if_empty_n( g_dst_mat_data_stream_0_V_empty_n ),
    .if_read( g_dst_mat_data_stream_0_V_read )
);

FIFO_EdgeDetect_Top_dst_mat_data_stream_0_V dst_mat_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .if_read_ce( dst_mat_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( dst_mat_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( dst_mat_data_stream_0_V_din ),
    .if_full_n( dst_mat_data_stream_0_V_full_n ),
    .if_write( dst_mat_data_stream_0_V_write ),
    .if_dout( dst_mat_data_stream_0_V_dout ),
    .if_empty_n( dst_mat_data_stream_0_V_empty_n ),
    .if_read( dst_mat_data_stream_0_V_read )
);

FIFO_EdgeDetect_Top_dst_mat_data_stream_1_V dst_mat_data_stream_1_V_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .if_read_ce( dst_mat_data_stream_1_V_U_ap_dummy_ce ),
    .if_write_ce( dst_mat_data_stream_1_V_U_ap_dummy_ce ),
    .if_din( dst_mat_data_stream_1_V_din ),
    .if_full_n( dst_mat_data_stream_1_V_full_n ),
    .if_write( dst_mat_data_stream_1_V_write ),
    .if_dout( dst_mat_data_stream_1_V_dout ),
    .if_empty_n( dst_mat_data_stream_1_V_empty_n ),
    .if_read( dst_mat_data_stream_1_V_read )
);

FIFO_EdgeDetect_Top_dst_mat_data_stream_2_V dst_mat_data_stream_2_V_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .if_read_ce( dst_mat_data_stream_2_V_U_ap_dummy_ce ),
    .if_write_ce( dst_mat_data_stream_2_V_U_ap_dummy_ce ),
    .if_din( dst_mat_data_stream_2_V_din ),
    .if_full_n( dst_mat_data_stream_2_V_full_n ),
    .if_write( dst_mat_data_stream_2_V_write ),
    .if_dout( dst_mat_data_stream_2_V_dout ),
    .if_empty_n( dst_mat_data_stream_2_V_empty_n ),
    .if_read( dst_mat_data_stream_2_V_read )
);



always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_EdgeDetect_Top_AXIvideo2Mat112_U0
    if (ap_rst == 1'b1) begin
        ap_reg_procdone_EdgeDetect_Top_AXIvideo2Mat112_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_EdgeDetect_Top_AXIvideo2Mat112_U0 <= ap_const_logic_0;
        end else if ((EdgeDetect_Top_AXIvideo2Mat112_U0_ap_done == ap_const_logic_1)) begin
            ap_reg_procdone_EdgeDetect_Top_AXIvideo2Mat112_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_EdgeDetect_Top_CvtColor_1_U0
    if (ap_rst == 1'b1) begin
        ap_reg_procdone_EdgeDetect_Top_CvtColor_1_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_EdgeDetect_Top_CvtColor_1_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == EdgeDetect_Top_CvtColor_1_U0_ap_done)) begin
            ap_reg_procdone_EdgeDetect_Top_CvtColor_1_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_EdgeDetect_Top_CvtColor_U0
    if (ap_rst == 1'b1) begin
        ap_reg_procdone_EdgeDetect_Top_CvtColor_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_EdgeDetect_Top_CvtColor_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == EdgeDetect_Top_CvtColor_U0_ap_done)) begin
            ap_reg_procdone_EdgeDetect_Top_CvtColor_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_EdgeDetect_Top_GaussianBlur_U0
    if (ap_rst == 1'b1) begin
        ap_reg_procdone_EdgeDetect_Top_GaussianBlur_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_EdgeDetect_Top_GaussianBlur_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == EdgeDetect_Top_GaussianBlur_U0_ap_done)) begin
            ap_reg_procdone_EdgeDetect_Top_GaussianBlur_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_EdgeDetect_Top_ImgProcess_0_0_128_128_U0
    if (ap_rst == 1'b1) begin
        ap_reg_procdone_EdgeDetect_Top_ImgProcess_0_0_128_128_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_EdgeDetect_Top_ImgProcess_0_0_128_128_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == EdgeDetect_Top_ImgProcess_0_0_128_128_U0_ap_done)) begin
            ap_reg_procdone_EdgeDetect_Top_ImgProcess_0_0_128_128_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0
    if (ap_rst == 1'b1) begin
        ap_reg_procdone_EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_ap_done)) begin
            ap_reg_procdone_EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_CS <= ap_const_logic_0;
end

always @ (EdgeDetect_Top_AXIvideo2Mat112_U0_ap_idle or EdgeDetect_Top_GaussianBlur_U0_ap_idle or EdgeDetect_Top_CvtColor_U0_ap_idle or EdgeDetect_Top_ImgProcess_0_0_128_128_U0_ap_idle or EdgeDetect_Top_CvtColor_1_U0_ap_idle or EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_ap_idle) begin
    if (((EdgeDetect_Top_AXIvideo2Mat112_U0_ap_idle == ap_const_logic_1) & (ap_const_logic_1 == EdgeDetect_Top_GaussianBlur_U0_ap_idle) & (ap_const_logic_1 == EdgeDetect_Top_CvtColor_U0_ap_idle) & (ap_const_logic_1 == EdgeDetect_Top_ImgProcess_0_0_128_128_U0_ap_idle) & (ap_const_logic_1 == EdgeDetect_Top_CvtColor_1_U0_ap_idle) & (ap_const_logic_1 == EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_ap_idle))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_ap_done) begin
    if ((ap_const_logic_1 == EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_ap_done)) begin
        ap_sig_hs_done = ap_const_logic_1;
    end else begin
        ap_sig_hs_done = ap_const_logic_0;
    end
end

assign EdgeDetect_Top_AXIvideo2Mat112_U0_ap_continue = ap_const_logic_1;

assign EdgeDetect_Top_AXIvideo2Mat112_U0_ap_start = ap_start;

assign EdgeDetect_Top_AXIvideo2Mat112_U0_cols = {{cols[(ap_const_lv32_8 - 32'd1) : ap_const_lv32_0]}};

assign EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_data_V_dout = input_V_data_V_dout;

assign EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_data_V_empty_n = input_V_data_V_empty_n;

assign EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_dest_V_dout = input_V_dest_V_dout;

assign EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_dest_V_empty_n = input_V_dest_V_empty_n;

assign EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_id_V_dout = input_V_id_V_dout;

assign EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_id_V_empty_n = input_V_id_V_empty_n;

assign EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_keep_V_dout = input_V_keep_V_dout;

assign EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_keep_V_empty_n = input_V_keep_V_empty_n;

assign EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_last_V_dout = input_V_last_V_dout;

assign EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_last_V_empty_n = input_V_last_V_empty_n;

assign EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_strb_V_dout = input_V_strb_V_dout;

assign EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_strb_V_empty_n = input_V_strb_V_empty_n;

assign EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_user_V_dout = input_V_user_V_dout;

assign EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_user_V_empty_n = input_V_user_V_empty_n;

assign EdgeDetect_Top_AXIvideo2Mat112_U0_rows = {{rows[(ap_const_lv32_8 - 32'd1) : ap_const_lv32_0]}};

assign EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_0_V_full_n = src_mat_data_stream_0_V_full_n;

assign EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_1_V_full_n = src_mat_data_stream_1_V_full_n;

assign EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_2_V_full_n = src_mat_data_stream_2_V_full_n;

assign EdgeDetect_Top_AXIvideo2Mat112_U0_threashold = threashold;

assign EdgeDetect_Top_AXIvideo2Mat112_U0_threashold_out_full_n = threashold_channel_full_n;

assign EdgeDetect_Top_CvtColor_1_U0_ap_continue = ap_const_logic_1;

assign EdgeDetect_Top_CvtColor_1_U0_ap_start = ap_start;

assign EdgeDetect_Top_CvtColor_1_U0_cols = {{cols[(ap_const_lv32_8 - 32'd1) : ap_const_lv32_0]}};

assign EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_0_V_full_n = dst_mat_data_stream_0_V_full_n;

assign EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_1_V_full_n = dst_mat_data_stream_1_V_full_n;

assign EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_2_V_full_n = dst_mat_data_stream_2_V_full_n;

assign EdgeDetect_Top_CvtColor_1_U0_p_src_data_stream_V_dout = g_dst_mat_data_stream_0_V_dout;

assign EdgeDetect_Top_CvtColor_1_U0_p_src_data_stream_V_empty_n = g_dst_mat_data_stream_0_V_empty_n;

assign EdgeDetect_Top_CvtColor_1_U0_rows = {{rows[(ap_const_lv32_8 - 32'd1) : ap_const_lv32_0]}};

assign EdgeDetect_Top_CvtColor_U0_ap_continue = ap_const_logic_1;

assign EdgeDetect_Top_CvtColor_U0_ap_start = ap_start;

assign EdgeDetect_Top_CvtColor_U0_cols = {{cols[(ap_const_lv32_8 - 32'd1) : ap_const_lv32_0]}};

assign EdgeDetect_Top_CvtColor_U0_p_dst_data_stream_V_full_n = g_src_mat_data_stream_0_V_full_n;

assign EdgeDetect_Top_CvtColor_U0_p_src_data_stream_0_V_dout = b_src_mat_data_stream_0_V_dout;

assign EdgeDetect_Top_CvtColor_U0_p_src_data_stream_0_V_empty_n = b_src_mat_data_stream_0_V_empty_n;

assign EdgeDetect_Top_CvtColor_U0_p_src_data_stream_1_V_dout = b_src_mat_data_stream_1_V_dout;

assign EdgeDetect_Top_CvtColor_U0_p_src_data_stream_1_V_empty_n = b_src_mat_data_stream_1_V_empty_n;

assign EdgeDetect_Top_CvtColor_U0_p_src_data_stream_2_V_dout = b_src_mat_data_stream_2_V_dout;

assign EdgeDetect_Top_CvtColor_U0_p_src_data_stream_2_V_empty_n = b_src_mat_data_stream_2_V_empty_n;

assign EdgeDetect_Top_CvtColor_U0_rows = {{rows[(ap_const_lv32_8 - 32'd1) : ap_const_lv32_0]}};

assign EdgeDetect_Top_GaussianBlur_U0_ap_continue = ap_const_logic_1;

assign EdgeDetect_Top_GaussianBlur_U0_ap_start = ap_start;

assign EdgeDetect_Top_GaussianBlur_U0_cols = {{cols[(ap_const_lv32_8 - 32'd1) : ap_const_lv32_0]}};

assign EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_0_V_full_n = b_src_mat_data_stream_0_V_full_n;

assign EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_1_V_full_n = b_src_mat_data_stream_1_V_full_n;

assign EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_2_V_full_n = b_src_mat_data_stream_2_V_full_n;

assign EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_0_V_dout = src_mat_data_stream_0_V_dout;

assign EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_0_V_empty_n = src_mat_data_stream_0_V_empty_n;

assign EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_1_V_dout = src_mat_data_stream_1_V_dout;

assign EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_1_V_empty_n = src_mat_data_stream_1_V_empty_n;

assign EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_2_V_dout = src_mat_data_stream_2_V_dout;

assign EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_2_V_empty_n = src_mat_data_stream_2_V_empty_n;

assign EdgeDetect_Top_GaussianBlur_U0_rows = {{rows[(ap_const_lv32_8 - 32'd1) : ap_const_lv32_0]}};

assign EdgeDetect_Top_ImgProcess_0_0_128_128_U0_ap_continue = ap_const_logic_1;

assign EdgeDetect_Top_ImgProcess_0_0_128_128_U0_ap_start = ap_start;

assign EdgeDetect_Top_ImgProcess_0_0_128_128_U0_height = {{rows[(ap_const_lv32_8 - 32'd1) : ap_const_lv32_0]}};

assign EdgeDetect_Top_ImgProcess_0_0_128_128_U0_p_dst_data_stream_V_full_n = g_dst_mat_data_stream_0_V_full_n;

assign EdgeDetect_Top_ImgProcess_0_0_128_128_U0_p_src_data_stream_V_dout = g_src_mat_data_stream_0_V_dout;

assign EdgeDetect_Top_ImgProcess_0_0_128_128_U0_p_src_data_stream_V_empty_n = g_src_mat_data_stream_0_V_empty_n;

assign EdgeDetect_Top_ImgProcess_0_0_128_128_U0_threashold_dout = threashold_channel_dout;

assign EdgeDetect_Top_ImgProcess_0_0_128_128_U0_threashold_empty_n = threashold_channel_empty_n;

assign EdgeDetect_Top_ImgProcess_0_0_128_128_U0_width = {{cols[(ap_const_lv32_8 - 32'd1) : ap_const_lv32_0]}};

assign EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_data_V_full_n = output_V_data_V_full_n;

assign EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_dest_V_full_n = output_V_dest_V_full_n;

assign EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_id_V_full_n = output_V_id_V_full_n;

assign EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_keep_V_full_n = output_V_keep_V_full_n;

assign EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_last_V_full_n = output_V_last_V_full_n;

assign EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_strb_V_full_n = output_V_strb_V_full_n;

assign EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_user_V_full_n = output_V_user_V_full_n;

assign EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_ap_continue = ap_sig_hs_continue;

assign EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_ap_start = ap_start;

assign EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_cols = {{cols[(ap_const_lv32_8 - 32'd1) : ap_const_lv32_0]}};

assign EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_0_V_dout = dst_mat_data_stream_0_V_dout;

assign EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_0_V_empty_n = dst_mat_data_stream_0_V_empty_n;

assign EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_1_V_dout = dst_mat_data_stream_1_V_dout;

assign EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_1_V_empty_n = dst_mat_data_stream_1_V_empty_n;

assign EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_2_V_dout = dst_mat_data_stream_2_V_dout;

assign EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_2_V_empty_n = dst_mat_data_stream_2_V_empty_n;

assign EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_rows = {{rows[(ap_const_lv32_8 - 32'd1) : ap_const_lv32_0]}};

assign ap_done = ap_sig_hs_done;

assign ap_ready = ap_sig_top_allready;

assign ap_sig_hs_continue = ap_const_logic_1;

assign ap_sig_top_allready = EdgeDetect_Top_AXIvideo2Mat112_U0_ap_ready;

assign b_src_mat_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign b_src_mat_data_stream_0_V_din = EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_0_V_din;

assign b_src_mat_data_stream_0_V_read = EdgeDetect_Top_CvtColor_U0_p_src_data_stream_0_V_read;

assign b_src_mat_data_stream_0_V_write = EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_0_V_write;

assign b_src_mat_data_stream_1_V_U_ap_dummy_ce = ap_const_logic_1;

assign b_src_mat_data_stream_1_V_din = EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_1_V_din;

assign b_src_mat_data_stream_1_V_read = EdgeDetect_Top_CvtColor_U0_p_src_data_stream_1_V_read;

assign b_src_mat_data_stream_1_V_write = EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_1_V_write;

assign b_src_mat_data_stream_2_V_U_ap_dummy_ce = ap_const_logic_1;

assign b_src_mat_data_stream_2_V_din = EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_2_V_din;

assign b_src_mat_data_stream_2_V_read = EdgeDetect_Top_CvtColor_U0_p_src_data_stream_2_V_read;

assign b_src_mat_data_stream_2_V_write = EdgeDetect_Top_GaussianBlur_U0_p_dst_data_stream_2_V_write;

assign dst_mat_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign dst_mat_data_stream_0_V_din = EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_0_V_din;

assign dst_mat_data_stream_0_V_read = EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_0_V_read;

assign dst_mat_data_stream_0_V_write = EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_0_V_write;

assign dst_mat_data_stream_1_V_U_ap_dummy_ce = ap_const_logic_1;

assign dst_mat_data_stream_1_V_din = EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_1_V_din;

assign dst_mat_data_stream_1_V_read = EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_1_V_read;

assign dst_mat_data_stream_1_V_write = EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_1_V_write;

assign dst_mat_data_stream_2_V_U_ap_dummy_ce = ap_const_logic_1;

assign dst_mat_data_stream_2_V_din = EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_2_V_din;

assign dst_mat_data_stream_2_V_read = EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_img_data_stream_2_V_read;

assign dst_mat_data_stream_2_V_write = EdgeDetect_Top_CvtColor_1_U0_p_dst_data_stream_2_V_write;

assign g_dst_mat_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign g_dst_mat_data_stream_0_V_din = EdgeDetect_Top_ImgProcess_0_0_128_128_U0_p_dst_data_stream_V_din;

assign g_dst_mat_data_stream_0_V_read = EdgeDetect_Top_CvtColor_1_U0_p_src_data_stream_V_read;

assign g_dst_mat_data_stream_0_V_write = EdgeDetect_Top_ImgProcess_0_0_128_128_U0_p_dst_data_stream_V_write;

assign g_src_mat_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign g_src_mat_data_stream_0_V_din = EdgeDetect_Top_CvtColor_U0_p_dst_data_stream_V_din;

assign g_src_mat_data_stream_0_V_read = EdgeDetect_Top_ImgProcess_0_0_128_128_U0_p_src_data_stream_V_read;

assign g_src_mat_data_stream_0_V_write = EdgeDetect_Top_CvtColor_U0_p_dst_data_stream_V_write;

assign input_V_data_V_read = EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_data_V_read;

assign input_V_dest_V_read = EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_dest_V_read;

assign input_V_id_V_read = EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_id_V_read;

assign input_V_keep_V_read = EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_keep_V_read;

assign input_V_last_V_read = EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_last_V_read;

assign input_V_strb_V_read = EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_strb_V_read;

assign input_V_user_V_read = EdgeDetect_Top_AXIvideo2Mat112_U0_input_V_user_V_read;

assign output_V_data_V_din = EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_data_V_din;

assign output_V_data_V_write = EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_data_V_write;

assign output_V_dest_V_din = EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_dest_V_din;

assign output_V_dest_V_write = EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_dest_V_write;

assign output_V_id_V_din = EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_id_V_din;

assign output_V_id_V_write = EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_id_V_write;

assign output_V_keep_V_din = EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_keep_V_din;

assign output_V_keep_V_write = EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_keep_V_write;

assign output_V_last_V_din = EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_last_V_din;

assign output_V_last_V_write = EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_last_V_write;

assign output_V_strb_V_din = EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_strb_V_din;

assign output_V_strb_V_write = EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_strb_V_write;

assign output_V_user_V_din = EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_user_V_din;

assign output_V_user_V_write = EdgeDetect_Top_Mat2AXIvideo_24_128_128_32_U0_AXI_video_strm_V_user_V_write;

assign src_mat_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign src_mat_data_stream_0_V_din = EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_0_V_din;

assign src_mat_data_stream_0_V_read = EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_0_V_read;

assign src_mat_data_stream_0_V_write = EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_0_V_write;

assign src_mat_data_stream_1_V_U_ap_dummy_ce = ap_const_logic_1;

assign src_mat_data_stream_1_V_din = EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_1_V_din;

assign src_mat_data_stream_1_V_read = EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_1_V_read;

assign src_mat_data_stream_1_V_write = EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_1_V_write;

assign src_mat_data_stream_2_V_U_ap_dummy_ce = ap_const_logic_1;

assign src_mat_data_stream_2_V_din = EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_2_V_din;

assign src_mat_data_stream_2_V_read = EdgeDetect_Top_GaussianBlur_U0_p_src_data_stream_2_V_read;

assign src_mat_data_stream_2_V_write = EdgeDetect_Top_AXIvideo2Mat112_U0_src_mat_data_stream_2_V_write;

assign threashold_channel_U_ap_dummy_ce = ap_const_logic_1;

assign threashold_channel_din = EdgeDetect_Top_AXIvideo2Mat112_U0_threashold_out_din;

assign threashold_channel_read = EdgeDetect_Top_ImgProcess_0_0_128_128_U0_threashold_read;

assign threashold_channel_write = EdgeDetect_Top_AXIvideo2Mat112_U0_threashold_out_write;


endmodule //EdgeDetect_Top

