// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xexample.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XExample_CfgInitialize(XExample *InstancePtr, XExample_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Hls_macc_periph_bus_BaseAddress = ConfigPtr->Hls_macc_periph_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

u32 XExample_Get_A_BaseAddress(XExample *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Hls_macc_periph_bus_BaseAddress + XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_A_BASE);
}

u32 XExample_Get_A_HighAddress(XExample *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Hls_macc_periph_bus_BaseAddress + XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_A_HIGH);
}

u32 XExample_Get_A_TotalBytes(XExample *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_A_HIGH - XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_A_BASE + 1);
}

u32 XExample_Get_A_BitWidth(XExample *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEXAMPLE_HLS_MACC_PERIPH_BUS_WIDTH_A;
}

u32 XExample_Get_A_Depth(XExample *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEXAMPLE_HLS_MACC_PERIPH_BUS_DEPTH_A;
}

u32 XExample_Write_A_Words(XExample *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_A_HIGH - XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Hls_macc_periph_bus_BaseAddress + XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_A_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XExample_Read_A_Words(XExample *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_A_HIGH - XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Hls_macc_periph_bus_BaseAddress + XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_A_BASE + (offset + i)*4);
    }
    return length;
}

u32 XExample_Write_A_Bytes(XExample *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_A_HIGH - XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Hls_macc_periph_bus_BaseAddress + XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_A_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XExample_Read_A_Bytes(XExample *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_A_HIGH - XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Hls_macc_periph_bus_BaseAddress + XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_A_BASE + offset + i);
    }
    return length;
}

u32 XExample_Get_B_BaseAddress(XExample *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Hls_macc_periph_bus_BaseAddress + XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_B_BASE);
}

u32 XExample_Get_B_HighAddress(XExample *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Hls_macc_periph_bus_BaseAddress + XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_B_HIGH);
}

u32 XExample_Get_B_TotalBytes(XExample *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_B_HIGH - XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_B_BASE + 1);
}

u32 XExample_Get_B_BitWidth(XExample *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEXAMPLE_HLS_MACC_PERIPH_BUS_WIDTH_B;
}

u32 XExample_Get_B_Depth(XExample *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEXAMPLE_HLS_MACC_PERIPH_BUS_DEPTH_B;
}

u32 XExample_Write_B_Words(XExample *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_B_HIGH - XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_B_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Hls_macc_periph_bus_BaseAddress + XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_B_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XExample_Read_B_Words(XExample *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_B_HIGH - XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_B_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Hls_macc_periph_bus_BaseAddress + XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_B_BASE + (offset + i)*4);
    }
    return length;
}

u32 XExample_Write_B_Bytes(XExample *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_B_HIGH - XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_B_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Hls_macc_periph_bus_BaseAddress + XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_B_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XExample_Read_B_Bytes(XExample *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_B_HIGH - XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_B_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Hls_macc_periph_bus_BaseAddress + XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_B_BASE + offset + i);
    }
    return length;
}

