// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// HLS_MACC_PERIPH_BUS
// 0x100 ~
// 0x1ff : Memory 'A' (50 * 32b)
//         Word n : bit [31:0] - A[n]
// 0x200 ~
// 0x2ff : Memory 'B' (50 * 32b)
//         Word n : bit [31:0] - B[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_A_BASE 0x100
#define XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_A_HIGH 0x1ff
#define XEXAMPLE_HLS_MACC_PERIPH_BUS_WIDTH_A     32
#define XEXAMPLE_HLS_MACC_PERIPH_BUS_DEPTH_A     50
#define XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_B_BASE 0x200
#define XEXAMPLE_HLS_MACC_PERIPH_BUS_ADDR_B_HIGH 0x2ff
#define XEXAMPLE_HLS_MACC_PERIPH_BUS_WIDTH_B     32
#define XEXAMPLE_HLS_MACC_PERIPH_BUS_DEPTH_B     50

