// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#1 "C:/Users/zengh/Documents/xup/axi_stream_no_side_channel_data/example.cpp"
#1 "<built-in>"
#1 "<command-line>"
#1 "C:/Users/zengh/Documents/xup/axi_stream_no_side_channel_data/example.cpp"
#92 "C:/Users/zengh/Documents/xup/axi_stream_no_side_channel_data/example.cpp"

#ifndef HLS_FASTSIM
#include "apatb_example.h"
#endif
#define example(...) AESL_ORIG_DUT_example(__VA_ARGS__)
#92 "C:/Users/zengh/Documents/xup/axi_stream_no_side_channel_data/example.cpp"
void example(int A[50], int B[50]) {
#pragma HLS INTERFACE axis port=A
#pragma HLS INTERFACE axis port=B

  int i;

  for(i = 0; i < 50; i++){
    B[i] = A[i] + 5;
  }
}
#undef example

#101 "C:/Users/zengh/Documents/xup/axi_stream_no_side_channel_data/example.cpp"
