// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module EdgeDetect_Top_CvtColor (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        rows,
        cols,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 4'b1;
parameter    ap_ST_st2_fsm_1 = 4'b10;
parameter    ap_ST_pp0_stg0_fsm_2 = 4'b100;
parameter    ap_ST_st8_fsm_3 = 4'b1000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv9_1 = 9'b1;
parameter    ap_const_lv32_16 = 32'b10110;
parameter    ap_const_lv32_1D = 32'b11101;
parameter    ap_const_lv32_15 = 32'b10101;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv28_74BC6 = 28'b1110100101111000110;
parameter    ap_const_lv29_1322D0 = 29'b100110010001011010000;
parameter    ap_const_lv30_259168 = 30'b1001011001000101101000;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [8:0] rows;
input  [8:0] cols;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_V_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm = 4'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_23;
reg   [8:0] j_i_reg_140;
reg    ap_sig_bdd_55;
wire   [0:0] exitcond2_i_fu_151_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_67;
wire   [8:0] i_fu_156_p2;
reg   [8:0] i_reg_285;
wire   [0:0] exitcond_i_fu_162_p2;
reg   [0:0] exitcond_i_reg_290;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_2;
reg    ap_sig_bdd_78;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_sig_bdd_92;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_290_pp0_it3;
reg    ap_sig_bdd_104;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_290_pp0_it1;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_290_pp0_it2;
wire   [8:0] j_fu_167_p2;
reg   [7:0] tmp_167_reg_299;
reg   [7:0] tmp_168_reg_304;
reg   [7:0] ap_reg_ppstg_tmp_168_reg_304_pp0_it2;
reg   [7:0] tmp_169_reg_309;
wire   [28:0] grp_fu_246_p3;
reg   [28:0] p_Val2_69_reg_314;
wire   [7:0] p_Val2_s_fu_238_p3;
reg   [7:0] p_Val2_s_reg_319;
reg   [8:0] i_i_reg_129;
reg    ap_sig_cseq_ST_st8_fsm_3;
reg    ap_sig_bdd_151;
wire   [29:0] grp_fu_260_p3;
wire   [0:0] tmp_fu_194_p3;
wire   [7:0] p_Val2_71_fu_185_p4;
wire   [7:0] tmp_1_i_i_i_i_fu_201_p1;
wire   [7:0] p_Val2_72_fu_212_p2;
wire   [0:0] tmp_164_fu_205_p3;
wire   [0:0] tmp_165_fu_218_p3;
wire   [0:0] p_Result_3_i_i_i_i_not_fu_226_p2;
wire   [0:0] not_carry_fu_232_p2;
wire   [7:0] grp_fu_246_p0;
wire   [19:0] grp_fu_246_p1;
wire   [28:0] r_V_i_i_fu_253_p2;
wire   [7:0] r_V_i_i_fu_253_p0;
wire   [21:0] r_V_i_i_fu_253_p1;
wire   [7:0] grp_fu_260_p0;
wire   [22:0] grp_fu_260_p1;
wire   [28:0] grp_fu_260_p2;
reg   [3:0] ap_NS_fsm;
wire   [27:0] grp_fu_246_p00;
wire   [29:0] grp_fu_260_p00;
wire   [29:0] grp_fu_260_p20;
wire   [28:0] r_V_i_i_fu_253_p00;


EdgeDetect_Top_mac_muladd_8ns_20ns_29ns_29_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 20 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
EdgeDetect_Top_mac_muladd_8ns_20ns_29ns_29_1_U55(
    .din0( grp_fu_246_p0 ),
    .din1( grp_fu_246_p1 ),
    .din2( r_V_i_i_fu_253_p2 ),
    .dout( grp_fu_246_p3 )
);

EdgeDetect_Top_mul_mul_8ns_22ns_29_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 29 ))
EdgeDetect_Top_mul_mul_8ns_22ns_29_1_U56(
    .din0( r_V_i_i_fu_253_p0 ),
    .din1( r_V_i_i_fu_253_p1 ),
    .dout( r_V_i_i_fu_253_p2 )
);

EdgeDetect_Top_mac_muladd_8ns_23ns_29ns_30_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 23 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 30 ))
EdgeDetect_Top_mac_muladd_8ns_23ns_29ns_30_1_U57(
    .din0( grp_fu_260_p0 ),
    .din1( grp_fu_260_p1 ),
    .din2( grp_fu_260_p2 ),
    .dout( grp_fu_260_p3 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond2_i_fu_151_p2 == ap_const_lv1_0))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(exitcond_i_fu_162_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond2_i_fu_151_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (exitcond_i_fu_162_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond2_i_fu_151_p2 == ap_const_lv1_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(exitcond_i_fu_162_p2 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond2_i_fu_151_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_3)) begin
        i_i_reg_129 <= i_reg_285;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_55)) begin
        i_i_reg_129 <= ap_const_lv9_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (exitcond_i_fu_162_p2 == ap_const_lv1_0))) begin
        j_i_reg_140 <= j_fu_167_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond2_i_fu_151_p2 == ap_const_lv1_0))) begin
        j_i_reg_140 <= ap_const_lv9_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        ap_reg_ppstg_exitcond_i_reg_290_pp0_it1 <= exitcond_i_reg_290;
        exitcond_i_reg_290 <= exitcond_i_fu_162_p2;
    end
end

always @ (posedge ap_clk) begin
    if (~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
        ap_reg_ppstg_exitcond_i_reg_290_pp0_it2 <= ap_reg_ppstg_exitcond_i_reg_290_pp0_it1;
        ap_reg_ppstg_exitcond_i_reg_290_pp0_it3 <= ap_reg_ppstg_exitcond_i_reg_290_pp0_it2;
        ap_reg_ppstg_tmp_168_reg_304_pp0_it2 <= tmp_168_reg_304;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        i_reg_285 <= i_fu_156_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_i_reg_290_pp0_it1))) begin
        p_Val2_69_reg_314 <= grp_fu_246_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_i_reg_290_pp0_it2))) begin
        p_Val2_s_reg_319 <= p_Val2_s_fu_238_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_i_reg_290 == ap_const_lv1_0) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        tmp_167_reg_299 <= p_src_data_stream_0_V_dout;
        tmp_168_reg_304 <= p_src_data_stream_1_V_dout;
        tmp_169_reg_309 <= p_src_data_stream_2_V_dout;
    end
end

always @ (ap_done_reg or exitcond2_i_fu_151_p2 or ap_sig_cseq_ST_st2_fsm_1) begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond2_i_fu_151_p2 == ap_const_lv1_0)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (exitcond2_i_fu_151_p2 or ap_sig_cseq_ST_st2_fsm_1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond2_i_fu_151_p2 == ap_const_lv1_0))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_78) begin
    if (ap_sig_bdd_78) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_23) begin
    if (ap_sig_bdd_23) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_67) begin
    if (ap_sig_bdd_67) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_151) begin
    if (ap_sig_bdd_151) begin
        ap_sig_cseq_ST_st8_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_3 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_92 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_i_reg_290_pp0_it3 or ap_sig_bdd_104 or ap_reg_ppiten_pp0_it4) begin
    if (((ap_const_lv1_0 == ap_reg_ppstg_exitcond_i_reg_290_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        p_dst_data_stream_V_write = ap_const_logic_1;
    end else begin
        p_dst_data_stream_V_write = ap_const_logic_0;
    end
end

always @ (exitcond_i_reg_290 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_92 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_104 or ap_reg_ppiten_pp0_it4) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_i_reg_290 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        p_src_data_stream_0_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_0_V_read = ap_const_logic_0;
    end
end

always @ (exitcond_i_reg_290 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_92 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_104 or ap_reg_ppiten_pp0_it4) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_i_reg_290 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        p_src_data_stream_1_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_1_V_read = ap_const_logic_0;
    end
end

always @ (exitcond_i_reg_290 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_92 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_104 or ap_reg_ppiten_pp0_it4) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_i_reg_290 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))))) begin
        p_src_data_stream_2_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_2_V_read = ap_const_logic_0;
    end
end
always @ (ap_CS_fsm or ap_sig_bdd_55 or exitcond2_i_fu_151_p2 or exitcond_i_fu_162_p2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_92 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_104 or ap_reg_ppiten_pp0_it4) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_55) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if (~(exitcond2_i_fu_151_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_pp0_stg0_fsm_2 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(exitcond_i_fu_162_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_92 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4))) & ~(exitcond_i_fu_162_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_st8_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_st8_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end



always @ (p_dst_data_stream_V_full_n or ap_reg_ppstg_exitcond_i_reg_290_pp0_it3) begin
    ap_sig_bdd_104 = ((p_dst_data_stream_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_i_reg_290_pp0_it3));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_151 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_23 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_start or ap_done_reg) begin
    ap_sig_bdd_55 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_67 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_78 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (p_src_data_stream_0_V_empty_n or p_src_data_stream_1_V_empty_n or p_src_data_stream_2_V_empty_n or exitcond_i_reg_290) begin
    ap_sig_bdd_92 = (((p_src_data_stream_0_V_empty_n == ap_const_logic_0) & (exitcond_i_reg_290 == ap_const_lv1_0)) | ((exitcond_i_reg_290 == ap_const_lv1_0) & (p_src_data_stream_1_V_empty_n == ap_const_logic_0)) | ((exitcond_i_reg_290 == ap_const_lv1_0) & (p_src_data_stream_2_V_empty_n == ap_const_logic_0)));
end

assign exitcond2_i_fu_151_p2 = (i_i_reg_129 == rows? 1'b1: 1'b0);

assign exitcond_i_fu_162_p2 = (j_i_reg_140 == cols? 1'b1: 1'b0);

assign grp_fu_246_p0 = grp_fu_246_p00;

assign grp_fu_246_p00 = tmp_169_reg_309;

assign grp_fu_246_p1 = ap_const_lv28_74BC6;

assign grp_fu_260_p0 = grp_fu_260_p00;

assign grp_fu_260_p00 = ap_reg_ppstg_tmp_168_reg_304_pp0_it2;

assign grp_fu_260_p1 = ap_const_lv30_259168;

assign grp_fu_260_p2 = grp_fu_260_p20;

assign grp_fu_260_p20 = p_Val2_69_reg_314;

assign i_fu_156_p2 = (i_i_reg_129 + ap_const_lv9_1);

assign j_fu_167_p2 = (j_i_reg_140 + ap_const_lv9_1);

assign not_carry_fu_232_p2 = (tmp_165_fu_218_p3 | p_Result_3_i_i_i_i_not_fu_226_p2);

assign p_Result_3_i_i_i_i_not_fu_226_p2 = (tmp_164_fu_205_p3 ^ ap_const_lv1_1);

assign p_Val2_71_fu_185_p4 = {{grp_fu_260_p3[ap_const_lv32_1D : ap_const_lv32_16]}};

assign p_Val2_72_fu_212_p2 = (p_Val2_71_fu_185_p4 + tmp_1_i_i_i_i_fu_201_p1);

assign p_Val2_s_fu_238_p3 = ((not_carry_fu_232_p2[0:0] === 1'b1) ? p_Val2_72_fu_212_p2 : ap_const_lv8_FF);

assign p_dst_data_stream_V_din = p_Val2_s_reg_319;

assign r_V_i_i_fu_253_p0 = r_V_i_i_fu_253_p00;

assign r_V_i_i_fu_253_p00 = tmp_167_reg_299;

assign r_V_i_i_fu_253_p1 = ap_const_lv29_1322D0;

assign tmp_164_fu_205_p3 = grp_fu_260_p3[ap_const_lv32_1D];

assign tmp_165_fu_218_p3 = p_Val2_72_fu_212_p2[ap_const_lv32_7];

assign tmp_1_i_i_i_i_fu_201_p1 = tmp_fu_194_p3;

assign tmp_fu_194_p3 = grp_fu_260_p3[ap_const_lv32_15];


endmodule //EdgeDetect_Top_CvtColor

